import { ApiProperty } from '@nestjs/swagger';

export class AuthTokensDto {
  @ApiProperty({
    description: 'JWT access token for API requests',
    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
  })
  accessToken: string;

  @ApiProperty({
    description: 'Refresh token for obtaining new access tokens',
    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
  })
  refreshToken: string;

  @ApiProperty({
    description: 'Token type',
    example: 'Bearer',
  })
  tokenType: string;

  @ApiProperty({
    description: 'Access token expiration time in seconds (0 means no expiration)',
    example: 0,
  })
  expiresIn: number;
}

export class AuthUserDto {
  @ApiProperty({
    description: 'User ID',
    example: 'clp123abc456def789',
  })
  id: string;

  @ApiProperty({
    description: 'User email',
    example: 'user@example.com',
  })
  email: string;

  @ApiProperty({
    description: 'User full name (if available)',
    example: 'John Doe',
    required: false,
  })
  fullName?: string;

  @ApiProperty({
    description: 'User first name (if available)',
    example: 'John',
    required: false,
  })
  firstName?: string;

  @ApiProperty({
    description: 'User last name (if available)',
    example: 'Doe',
    required: false,
  })
  lastName?: string;

  @ApiProperty({
    description: 'Whether user has completed onboarding',
    example: false,
  })
  hasCompletedOnboarding: boolean;

  @ApiProperty({
    description: 'Last login timestamp',
    example: '2024-01-15T10:30:00.000Z',
  })
  lastLoginAt: string;

  @ApiProperty({
    description: 'Whether user has used their free recipe',
    example: false,
  })
  freeRecipeUsed: boolean;

  @ApiProperty({
    description: 'Number of recipes generated by user',
    example: 0,
  })
  recipeGenerationCount: number;

  @ApiProperty({
    description: 'User subscription status',
    example: {
      hasActiveSubscription: false,
      plan: null,
      canGenerateRecipes: true,
      reason: 'Free recipe available'
    },
  })
  subscriptionStatus: {
    hasActiveSubscription: boolean;
    plan: string | null;
    canGenerateRecipes: boolean;
    reason: string;
  };
}

export class AuthResponseDto {
  @ApiProperty({
    description: 'Authentication tokens',
    type: AuthTokensDto,
  })
  tokens: AuthTokensDto;

  @ApiProperty({
    description: 'User information',
    type: AuthUserDto,
  })
  user: AuthUserDto;
}

export class RefreshTokenDto {
  @ApiProperty({
    description: 'Refresh token',
    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
  })
  refreshToken: string;
} 