import { ApiProperty } from '@nestjs/swagger';

export class MealDto {
  @ApiProperty({
    description: 'Name of the meal/dish',
    example: 'Chicken Adobo with Jasmine Rice',
  })
  name: string;

  @ApiProperty({
    description: 'Estimated cooking time',
    example: '45 minutes',
  })
  estimatedCookTime: string;

  @ApiProperty({
    description: 'Estimated calories per serving',
    example: '520 calories per serving',
  })
  calories: string;

  @ApiProperty({
    description: 'Rating of the recipe (3.5-5.0)',
    example: 4.7,
    minimum: 3.5,
    maximum: 5.0,
  })
  rating: number;

  @ApiProperty({
    description: 'List of ingredients with measurements',
    example: [
      '1 kg chicken thighs, bone-in',
      '2 cups jasmine rice',
      '1/2 cup soy sauce',
      '1/4 cup white vinegar',
      '6 cloves garlic, minced',
    ],
    type: [String],
  })
  ingredients: string[];

  @ApiProperty({
    description: 'Step-by-step cooking instructions',
    example: [
      'Marinate chicken in soy sauce and vinegar for 30 minutes',
      'Heat oil in a large pan and brown the chicken pieces',
      'Add garlic and cook until fragrant',
      'Simmer covered for 30-40 minutes until tender',
      'Serve over steamed jasmine rice',
    ],
    type: [String],
  })
  instructions: string[];

  @ApiProperty({
    description: 'Professional cooking tips and tricks',
    example: [
      'Use bone-in chicken thighs for maximum flavor',
      'Don\'t stir the chicken while braising for best results',
      'The sauce should be tangy with a hint of sweetness',
    ],
    type: [String],
  })
  proTips: string[];

  @ApiProperty({
    description: 'Base64-encoded image of the meal generated by AI',
    example: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAv/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCdABmX/9k=',
  })
  image: string;
}

export class RecipeResponseDto {
  @ApiProperty({
    description: 'Array of generated meals',
    type: [MealDto],
  })
  meals: MealDto[];

  @ApiProperty({
    description: 'Location/country used for cuisine style',
    example: 'Italy',
  })
  location: string;

  @ApiProperty({
    description: 'AI provider used to generate the recipes',
    example: 'gemini',
    enum: ['gemini', 'deepseek'],
  })
  provider: string;
}

export class RecipeErrorDto {
  @ApiProperty({
    description: 'HTTP status code',
    example: 400,
  })
  statusCode: number;

  @ApiProperty({
    description: 'Error message',
    example: 'Failed to generate recipes',
  })
  message: string;

  @ApiProperty({
    description: 'Error type',
    example: 'Bad Request',
  })
  error: string;
} 